server:
  prefork: false

  database:
    host: 00.000.00.247
    port: 5433
    user: user
    password: pass
    name: order
    dialect: postgres
    debug: true
    max_open_conns: 20
    max_idle_conns: 15
    max_conn_max_lifetime: 10m0s

  telegram:
    bot_key: "22222:ssss-4344"
    bot_debug: true
