version: '3.1'
services:
  postgres:
    image: postgres:15.8-alpine
    restart: no
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: my_hub
    ports:
      - "5499:5432"
